### ISSUE TITLE
LR Settings Backwards Compatibility

### ISSUE THREAD

**Issue by RTO-Chatter** [RTO-Chatter/ACE-TFAR-Setter#11]
Current Layout has LR as index 2 of the profile, needs to be copied to index 1 of index 2, to allow array storage.

**Comment by M3ales** [comment]
TFAR radio data has fixed size, can do check using that, and knowledge of what data would be at start of it (mostly strings I think), Use `typeName`?

**Comment by RTO-Chatter** [comment]
isEqualTypeArray [[],[]] is another way we could check, If equal to that, continue, else, fix

**Comment by RTO-Chatter** [comment]
Fix implemented with #d3a1de2
