### ISSUE TITLE
Vehicle LR Support

### ISSUE THREAD

**Issue by M3ales** [RTO-Chatter/ACE-TFAR-Setter#6]
Already WIP.

Allow storage and loading of Vehicle Long Ranges.

## Considerations
- There is no TFAR method for setting Vehicle LR directly.
- Needs to ensure VLR is saved.
- Needs to use LR storage array and have backwards comparability to prevent a breaking API change if possible.
- Will the interaction be on the vehicle? or on the player under equipment?

**Comment by M3ales** [comment]
I'd prefer to keep it on the player, under equipment since then it is always active, we just need to have a `condition="if(vehicle player == player) && //has vlr"` to show it.

**Comment by M3ales** [comment]
Also worth noting that Both should become All if we add VLR since you'd be loading 3 things then.

**Comment by RTO-Chatter** [comment]
Implemented and Complete
